// <auto-generated />
using System;
using Appointment.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Appointment.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Appointment.Domain.Entities.City", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Adana"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Adıyaman"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Afyonkarahisar"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Ağrı"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Aksaray"
                        },
                        new
                        {
                            Id = "6",
                            Name = "Amasya"
                        },
                        new
                        {
                            Id = "7",
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = "8",
                            Name = "Antalya"
                        },
                        new
                        {
                            Id = "9",
                            Name = "Ardahan"
                        },
                        new
                        {
                            Id = "10",
                            Name = "Artvin"
                        },
                        new
                        {
                            Id = "11",
                            Name = "Aydın"
                        },
                        new
                        {
                            Id = "12",
                            Name = "Balıkesir"
                        },
                        new
                        {
                            Id = "13",
                            Name = "Bartın"
                        },
                        new
                        {
                            Id = "14",
                            Name = "Batman"
                        },
                        new
                        {
                            Id = "15",
                            Name = "Bayburt"
                        },
                        new
                        {
                            Id = "16",
                            Name = "Bilecik"
                        },
                        new
                        {
                            Id = "17",
                            Name = "Bingöl"
                        },
                        new
                        {
                            Id = "18",
                            Name = "Bitlis"
                        },
                        new
                        {
                            Id = "19",
                            Name = "Bolu"
                        },
                        new
                        {
                            Id = "20",
                            Name = "Burdur"
                        },
                        new
                        {
                            Id = "21",
                            Name = "Bursa"
                        },
                        new
                        {
                            Id = "22",
                            Name = "Çanakkale"
                        },
                        new
                        {
                            Id = "23",
                            Name = "Çankırı"
                        },
                        new
                        {
                            Id = "24",
                            Name = "Çorum"
                        },
                        new
                        {
                            Id = "25",
                            Name = "Denizli"
                        },
                        new
                        {
                            Id = "26",
                            Name = "Diyarbakır"
                        },
                        new
                        {
                            Id = "27",
                            Name = "Düzce"
                        },
                        new
                        {
                            Id = "28",
                            Name = "Edirne"
                        },
                        new
                        {
                            Id = "29",
                            Name = "Elazığ"
                        },
                        new
                        {
                            Id = "30",
                            Name = "Erzincan"
                        },
                        new
                        {
                            Id = "31",
                            Name = "Erzurum"
                        },
                        new
                        {
                            Id = "32",
                            Name = "Eskişehir"
                        },
                        new
                        {
                            Id = "33",
                            Name = "Gaziantep"
                        },
                        new
                        {
                            Id = "34",
                            Name = "Giresun"
                        },
                        new
                        {
                            Id = "35",
                            Name = "Gümüşhane"
                        },
                        new
                        {
                            Id = "36",
                            Name = "Hakkari"
                        },
                        new
                        {
                            Id = "37",
                            Name = "Hatay"
                        },
                        new
                        {
                            Id = "38",
                            Name = "Iğdır"
                        },
                        new
                        {
                            Id = "39",
                            Name = "Isparta"
                        },
                        new
                        {
                            Id = "40",
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = "41",
                            Name = "İzmir"
                        },
                        new
                        {
                            Id = "42",
                            Name = "Kahramanmaraş"
                        },
                        new
                        {
                            Id = "43",
                            Name = "Karabük"
                        },
                        new
                        {
                            Id = "44",
                            Name = "Karaman"
                        },
                        new
                        {
                            Id = "45",
                            Name = "Kars"
                        },
                        new
                        {
                            Id = "46",
                            Name = "Kastamonu"
                        },
                        new
                        {
                            Id = "47",
                            Name = "Kayseri"
                        },
                        new
                        {
                            Id = "48",
                            Name = "Kilis"
                        },
                        new
                        {
                            Id = "49",
                            Name = "Kırıkkale"
                        },
                        new
                        {
                            Id = "50",
                            Name = "Kırklareli"
                        },
                        new
                        {
                            Id = "51",
                            Name = "Kırşehir"
                        },
                        new
                        {
                            Id = "52",
                            Name = "Kocaeli"
                        },
                        new
                        {
                            Id = "53",
                            Name = "Konya"
                        },
                        new
                        {
                            Id = "54",
                            Name = "Kütahya"
                        },
                        new
                        {
                            Id = "55",
                            Name = "Malatya"
                        },
                        new
                        {
                            Id = "56",
                            Name = "Manisa"
                        },
                        new
                        {
                            Id = "57",
                            Name = "Mardin"
                        },
                        new
                        {
                            Id = "58",
                            Name = "Mersin"
                        },
                        new
                        {
                            Id = "59",
                            Name = "Muğla"
                        },
                        new
                        {
                            Id = "60",
                            Name = "Muş"
                        },
                        new
                        {
                            Id = "61",
                            Name = "Nevşehir"
                        },
                        new
                        {
                            Id = "62",
                            Name = "Niğde"
                        },
                        new
                        {
                            Id = "63",
                            Name = "Ordu"
                        },
                        new
                        {
                            Id = "64",
                            Name = "Osmaniye"
                        },
                        new
                        {
                            Id = "65",
                            Name = "Rize"
                        },
                        new
                        {
                            Id = "66",
                            Name = "Sakarya"
                        },
                        new
                        {
                            Id = "67",
                            Name = "Samsun"
                        },
                        new
                        {
                            Id = "68",
                            Name = "Şanlıurfa"
                        },
                        new
                        {
                            Id = "69",
                            Name = "Siirt"
                        },
                        new
                        {
                            Id = "70",
                            Name = "Sinop"
                        },
                        new
                        {
                            Id = "71",
                            Name = "Sivas"
                        },
                        new
                        {
                            Id = "72",
                            Name = "Şırnak"
                        },
                        new
                        {
                            Id = "73",
                            Name = "Tekirdağ"
                        },
                        new
                        {
                            Id = "74",
                            Name = "Tokat"
                        },
                        new
                        {
                            Id = "75",
                            Name = "Trabzon"
                        },
                        new
                        {
                            Id = "76",
                            Name = "Tunceli"
                        },
                        new
                        {
                            Id = "77",
                            Name = "Uşak"
                        },
                        new
                        {
                            Id = "78",
                            Name = "Van"
                        },
                        new
                        {
                            Id = "79",
                            Name = "Yalova"
                        },
                        new
                        {
                            Id = "80",
                            Name = "Yozgat"
                        },
                        new
                        {
                            Id = "81",
                            Name = "Zonguldak"
                        });
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Doctor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PolyclinicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolyclinicId1")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PolyclinicId1");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Hospital", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityId1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId1");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.HospitalAppointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoctorId1")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId1");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Identity.AspRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "3",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Identity.AspUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Polyclinic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HospitalId1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId1");

                    b.ToTable("Polyclinics");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Appointment.Domain.Entities.Department", null)
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Appointment.Domain.Entities.Polyclinic", "Polyclinic")
                        .WithMany("Doctors")
                        .HasForeignKey("PolyclinicId1");

                    b.HasOne("Appointment.Domain.Entities.Identity.AspUser", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("Appointment.Domain.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Polyclinic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Hospital", b =>
                {
                    b.HasOne("Appointment.Domain.Entities.City", "City")
                        .WithMany("Hospitals")
                        .HasForeignKey("CityId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.HospitalAppointment", b =>
                {
                    b.HasOne("Appointment.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId1");

                    b.HasOne("Appointment.Domain.Entities.Identity.AspUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Polyclinic", b =>
                {
                    b.HasOne("Appointment.Domain.Entities.Hospital", "Hospital")
                        .WithMany("Polyclinics")
                        .HasForeignKey("HospitalId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Appointment.Domain.Entities.Identity.AspRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Appointment.Domain.Entities.Identity.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Appointment.Domain.Entities.Identity.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Appointment.Domain.Entities.Identity.AspRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Appointment.Domain.Entities.Identity.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Appointment.Domain.Entities.Identity.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Appointment.Domain.Entities.City", b =>
                {
                    b.Navigation("Hospitals");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Hospital", b =>
                {
                    b.Navigation("Polyclinics");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Identity.AspUser", b =>
                {
                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Appointment.Domain.Entities.Polyclinic", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
